language: objective-c
osx_image: xcode8.2
before_install:
 - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
 - rvm get head
 - gem install cocoapods -v '1.2.0.beta.1'
before_script: 
 - open -a Simulator
 - xcrun simctl list devices
 - xctool -version
 - xcodebuild -version -sdk
script:
 - xctool -showTasks -destination "name=iPhone 6s Plus" -project GovData.xcodeproj -scheme GovData -sdk iphonesimulator run-tests
