language: objective-c
osx_image: xcode7
before_script: 
 - open -a Simulator
 - xcrun simctl list devices
 - xctool -version
 - xcodebuild -version -sdk
 - xcode-select --print-path
script:
 - xctool -showTasks -destination "name=iPhone 6s Plus" -project GovData.xcodeproj -scheme GovData -sdk iphonesimulator build test
