language: objective-c
osx_image: xcode8.2
before_install:
 - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
 - rvm get head
 - gem install cocoapods -v '1.2.0.beta.1'
 - brew reinstall --HEAD xctool
before_script: 
 - open -a Simulator
 - xcrun simctl list devices
 - xctool -version
 - xcodebuild -version -sdk
script:
 - xctool -showTasks -destination "id=EB1167CF-3545-44BC-9D95-482D286F6C66" -project GovData.xcodeproj -scheme GovData -sdk iphonesimulator run-tests
