language: objective-c
osx_image: xcode8.2
before_install:
 - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
 - rvm get head
 - gem install cocoapods -v '1.2.0.beta.1'
before_script: 
 - open -a Simulator
 - xcrun simctl list devices
 - xcodebuild -version -sdk
script:
 - xcodebuild -workspace GovData.xcworkspace -scheme Tests -destination 'platform=iOS Simulator,id=EB1167CF-3545-44BC-9D95-482D286F6C66,OS=10.2' -sdk iphonesimulator build test
