language: objective-c
osx_image: xcode7
script:
  - xcrun instruments -s devices
# - open -a Simulator
# - xctool -scheme Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' test
