language: objective-c
osx_image: xcode7
script:
 - xcrun instruments -s devices
 - instruments -w "iPhone 6 (9.0) ["
 - xctool -scheme Tests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" test
